USE [master]
GO

CREATE DATABASE [PALAactual]
GO

ALTER DATABASE [PALAactual] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PALAactual].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [PALAactual] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PALAactual] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PALAactual] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PALAactual] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PALAactual] SET ARITHABORT OFF 
GO
ALTER DATABASE [PALAactual] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PALAactual] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PALAactual] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [PALAactual] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PALAactual] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PALAactual] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PALAactual] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PALAactual] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PALAactual] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PALAactual] SET  ENABLE_BROKER 
GO
ALTER DATABASE [PALAactual] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PALAactual] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PALAactual] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [PALAactual] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [PALAactual] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PALAactual] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PALAactual] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [PALAactual] SET RECOVERY FULL 
GO
ALTER DATABASE [PALAactual] SET  MULTI_USER 
GO
ALTER DATABASE [PALAactual] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PALAactual] SET DB_CHAINING OFF 
GO
ALTER DATABASE [PALAactual] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [PALAactual] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [PALAactual] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [PALAactual] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'PALAactual', N'ON'
GO
ALTER DATABASE [PALAactual] SET QUERY_STORE = OFF
GO
USE [PALAactual]
GO
/****** Object:  Table [dbo].[Asignatura]    Script Date: 11/22/2022 12:36:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Asignatura](
	[AsignaturaID] [int] IDENTITY(1,1) NOT NULL,
	[Nombre] [nvarchar](50) NULL,
 CONSTRAINT [PK_Asignatura] PRIMARY KEY CLUSTERED 
(
	[AsignaturaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[AsignaturaTarea]    Script Date: 11/22/2022 12:36:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AsignaturaTarea](
	[TareaID] [int] NULL,
	[AsignaturaID] [int] NULL
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Estudiante]    Script Date: 11/22/2022 12:36:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Estudiante](
	[EstudianteID] [int] IDENTITY(1,1) NOT NULL,
	[TableroID] [int] NOT NULL,
	[Estado] [nvarchar](50) NULL,
	[Nombre] [nvarchar](50) NULL,
	[Apellidos] [nvarchar](1) NULL,
	[Correo] [nvarchar](1) NULL,
	[Nomusuario] [nvarchar](1) NULL,
	[Contraseña] [nvarchar](50) NULL,
 CONSTRAINT [PK_Estudiante] PRIMARY KEY CLUSTERED 
(
	[EstudianteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tarea]    Script Date: 11/22/2022 12:36:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tarea](
	[TareaID] [int] IDENTITY(1,1) NOT NULL,
	[EstudianteID] [int] NULL,
	[Estado] [varchar](1) NULL,
	[Descripcion] [nvarchar](200) NULL,
	[Vencimiento] [date] NULL,
	[T_restante] [nvarchar](1) NULL,
 CONSTRAINT [PK_Tarea] PRIMARY KEY CLUSTERED 
(
	[TareaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[AsignaturaTarea]  WITH CHECK ADD  CONSTRAINT [FK_AsignaturaTarea_Asignatura] FOREIGN KEY([AsignaturaID])
REFERENCES [dbo].[Asignatura] ([AsignaturaID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AsignaturaTarea] CHECK CONSTRAINT [FK_AsignaturaTarea_Asignatura]
GO
ALTER TABLE [dbo].[AsignaturaTarea]  WITH CHECK ADD  CONSTRAINT [FK_AsignaturaTarea_Tarea] FOREIGN KEY([TareaID])
REFERENCES [dbo].[Tarea] ([TareaID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
ALTER TABLE [dbo].[AsignaturaTarea] CHECK CONSTRAINT [FK_AsignaturaTarea_Tarea]
GO
ALTER TABLE [dbo].[Tarea]  WITH CHECK ADD  CONSTRAINT [FK_Tarea_Estudiante] FOREIGN KEY([EstudianteID])
REFERENCES [dbo].[Estudiante] ([EstudianteID])
GO
ALTER TABLE [dbo].[Tarea] CHECK CONSTRAINT [FK_Tarea_Estudiante]
GO
USE [master]
GO
ALTER DATABASE [PALAactual] SET  READ_WRITE 
GO
