/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentations;

import data.CourseDao;
import data.StudentDao;
import entities.Course;
import entities.Student;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lopez
 */
public class FormUser extends javax.swing.JFrame {

    CourseDao cDao = new CourseDao();
    StudentDao sDao = new StudentDao();
    int stdId = 0;

    /**
     * Creates new form FormUser
     */
    public FormUser() {

        initComponents();
    }

    public FormUser(int id) {

        initComponents();
        stdId = id;
        this.fillTable();
        this.fillTableUser();
    }

    private void fillTable() {
        ArrayList<Course> courses = cDao.getCourseStdID(stdId);
        DefaultTableModel dtm = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String titulos[] = {"Course"};
        dtm.setColumnIdentifiers(titulos);
        for (Course c : courses) {
            Object[] fila = new Object[]{
                c.getName()
            };

            dtm.addRow(fila);
        }
        this.tableCoursesUser.setModel(dtm);
    }

    private void fillTableUser() {
        Student student = sDao.getStudent(stdId);
        this.userName.setText(student.getName());
        this.userLastName.setText(student.getLastNames());
        this.userUserName.setText(student.getUserName());
        this.userMail.setText(student.getEmail());
        this.userPw.setText(student.getPassword());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        Datos = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCoursesUser = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        coursesUserT = new javax.swing.JTextField();
        jBtnBack = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        editBtn = new javax.swing.JButton();
        userName = new javax.swing.JTextField();
        okBtn = new javax.swing.JButton();
        userLastName = new javax.swing.JTextField();
        userUserName = new javax.swing.JTextField();
        userPw = new javax.swing.JPasswordField();
        userMail = new javax.swing.JTextField();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Datos.setBackground(new java.awt.Color(199, 199, 187));
        Datos.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jPanel1.setBackground(new java.awt.Color(193, 171, 173));

        tableCoursesUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableCoursesUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCoursesUserMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCoursesUser);

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentations/icons/Add.png"))); // NOI18N
        addBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentations/icons/Eliminar.png"))); // NOI18N
        deleteBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jBtnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentations/icons/Retroceder.png"))); // NOI18N
        jBtnBack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jBtnBack)
                        .addGap(27, 27, 27)
                        .addComponent(addBtn)
                        .addGap(29, 29, 29)
                        .addComponent(deleteBtn))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                    .addComponent(coursesUserT))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jBtnBack, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addComponent(coursesUserT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Datos.addTab("Courses", jPanel1);

        jPanel2.setBackground(new java.awt.Color(193, 171, 173));

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentations/icons/Edit.png"))); // NOI18N
        editBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });

        okBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/presentations/icons/Ok.png"))); // NOI18N
        okBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        okBtn.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                okBtnFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                okBtnFocusLost(evt);
            }
        });
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        userLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userLastNameActionPerformed(evt);
            }
        });

        userPw.setText("jPasswordField1");

        userMail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userMailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(okBtn)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(editBtn)
                        .addComponent(userMail)
                        .addComponent(userPw, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)
                        .addComponent(userUserName)
                        .addComponent(userLastName)
                        .addComponent(userName)))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(editBtn)
                .addGap(24, 24, 24)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(userUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(userPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(okBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Datos.addTab("User", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Datos)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Datos)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        String cName = this.coursesUserT.getText();
        if (cName.equals("")) {
            JOptionPane.showMessageDialog(null, "Please write something", ":/", JOptionPane.ERROR_MESSAGE);
        } else {
            cDao.saveCourseStd(cName, stdId);
        }
        this.fillTable();
        this.coursesUserT.setText("");
        this.coursesUserT.requestFocus();
    }//GEN-LAST:event_addBtnActionPerformed

    private void tableCoursesUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCoursesUserMouseClicked
        // TODO add your handling code here:
        this.tableCoursesUser.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                if (e.getClickCount() == 1) {
                    getData();
                }
            }
        });
    }//GEN-LAST:event_tableCoursesUserMouseClicked

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        String cName = this.coursesUserT.getText();
        if (cName.equals("")) {
            JOptionPane.showMessageDialog(null, "Please select something", ":/", JOptionPane.ERROR_MESSAGE);
        } else {
            cDao.deleteCourse(cName);
        }
        this.fillTable();
        this.coursesUserT.setText("");
        this.coursesUserT.requestFocus();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void jBtnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBackActionPerformed
        FormLists lists = new FormLists(this.stdId);
        lists.setLocationRelativeTo(null);
        lists.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBtnBackActionPerformed

    private void userMailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userMailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userMailActionPerformed

    private void userLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userLastNameActionPerformed

    private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        this.userName.requestFocus();

    }//GEN-LAST:event_editBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed

        if (verifyChanges()) {
            int status = 2;
            String pw = String.valueOf(this.userPw.getPassword());
            Student student = new Student(this.stdId, status, this.userName.getText(), this.userLastName.getText(),
                    this.userMail.getText(), this.userUserName.getText(), pw);
            this.sDao.editStudent(student);

        }

    }//GEN-LAST:event_okBtnActionPerformed

    private void okBtnFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_okBtnFocusGained

    }//GEN-LAST:event_okBtnFocusGained

    private void okBtnFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_okBtnFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_okBtnFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormUser().setVisible(true);
            }
        });
    }

    private void getData() {
        int row = this.tableCoursesUser.getSelectedRow();
        String cName = this.tableCoursesUser.getValueAt(row, 0).toString();
        this.coursesUserT.setText(cName);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Datos;
    private javax.swing.JButton addBtn;
    private javax.swing.JTextField coursesUserT;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton jBtnBack;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton okBtn;
    private javax.swing.JTable tableCoursesUser;
    private javax.swing.JTextField userLastName;
    private javax.swing.JTextField userMail;
    private javax.swing.JTextField userName;
    private javax.swing.JPasswordField userPw;
    private javax.swing.JTextField userUserName;
    // End of variables declaration//GEN-END:variables

    private boolean verifyChanges() {
        Student student = sDao.getStudent(stdId);
        String n = student.getName();
        String lN = student.getLastNames();
        String nU = student.getUserName();
        String mU = student.getEmail();
        String pwU = student.getPassword();
        String pwF = String.valueOf(this.userPw.getPassword());
        System.out.println(n);
        System.out.println(lN);
        System.out.println(nU);
        System.out.println(pwU);
        System.out.println(pwF);
        
        

        if (n.equals(this.userName.getText()) && lN.equals(this.userLastName.getText()) && nU.equals(this.userUserName.getText())
                && pwU.equals(pwF) && mU.equals(this.userMail.getText())) {
            System.out.println("entré en el if");
            return false;
        } else {
            return true;

        }

    }
}
